# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65d110984b6b54afd8da8a49c8bbeb75568b33815281216c00195e408fb33e3330220d51abedb6d011d6a99b3747af9e1f485320415907a1942f81916bd0eed

test:
  secret_key_base: a24b03a60816c89966906a88b5357ab4f92e8495655012ce776ffa5241c3947c7bf01be9208ff59f487e755fbc78f0e5850b60d1a397a437cad0ae0d7b1ccd99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
